feat: PHC-1824 small tweaks to handle vcf and auto deploy to TRS
lifeomic/foundation-ingest pull request #24
Opened 2021-09-28 13:34 UTC by RyanRatcliff

updates workflow to handle 3 files, .xml, .pdf, .vcf also adds in the auto deploy to TRS

2021-09-28 19:06 UTC, RyanRatcliff commented
Still need to fix the tests and remove the conda dependency/build flows

2021-09-29 18:21 UTC, RyanRatcliff commented
@murrayln This is ready for you're review, in particular, please checkout the vcf code I grabbed from your branch and how that's being tested.  I mean look at it all, but that's the most important bit.  Since we only had one VCF I expect that that code will probably be updated several times once we start seeing more data and I want to make sure it's clear and seems easy for you to update code and tests.

2021-09-29 18:51 UTC, RyanRatcliff commented on src/util/vcf_etl.py
> +  bgzip_process.wait(timeout=14400)
@murrayln I think this is the only change I made, and that's just to make sure the bgzip completes before moving on.  Most likely it wouldn't have been an issue, but I didn't want to leave it to chance.

2021-09-30 20:01 UTC, anthonyroach requested changes
How does the docker container get published now that `docker-push.yml` is gone?

2021-09-30 20:05 UTC, RyanRatcliff commented
> How does the docker container get published now that `docker-push.yml` is gone?

it only gets pushed to TRS, since this container is only useful to us, I thought we'd only publish to our tool registry

2021-09-30 20:06 UTC, RyanRatcliff commented on .pdm.toml
> +[python]
> This file should not be checked in.

Understood, will remove

2021-09-30 20:10 UTC, RyanRatcliff commented on requirements.txt
> +pyyaml==5.4
> Why not use PDM for these deps rather than requirements.txt?

Because the actual container build is still using the requirements file.  I'm using PDM as the project infra/testing.  I was trying to keep things small, then come back around to update the DockerFile to use PDM as well.  But I can go ahead and add PDM to the Dockerfile/build as well.  Then this file will be gone.

2021-09-30 20:11 UTC, RyanRatcliff commented
> > How does the docker container get published now that `docker-push.yml` is gone?
> 
> it only gets pushed to TRS, since this container is only useful to us, I thought we'd only publish to our tool registry

I'm open to discussion if anyone doesn't like this idea.

2021-10-01 18:05 UTC, anthonyroach commented on requirements.txt
> +pyyaml==5.4
ah ok

2021-10-01 18:05 UTC, anthonyroach commented
> > > How does the docker container get published now that `docker-push.yml` is gone?
> > 
> > 
> > it only gets pushed to TRS, since this container is only useful to us, I thought we'd only publish to our tool registry
> 
> I'm open to discussion if anyone doesn't like this idea.

No, that's fine. I just didn't understand how it worked.

2021-10-01 18:06 UTC, RyanRatcliff commented on requirements.txt
> +pyyaml==5.4
I did update it to use PDM in the container itself this morning, so you should see that now

2021-10-01 18:07 UTC, anthonyroach approved these changes

2021-10-05 14:06 UTC, merged